### ISSUE TITLE
Campo Unidade Executora - Formulário de Detalhamento

### ISSUE THREAD

**Issue by kesiabomfa** [dados-mg/diarias#3]
Verificar com o Luís qual o campo do armazém SIAFI ele utiliza para o campo Unidade Executora - Formulário de Detalhamento.
![image](https://user-images.githubusercontent.com/52920939/111483593-ad816980-8713-11eb-81dd-416fefa887cb.png)

O campo é composto por Unidade Executora código + descrição
No armazém é possível consultar os campos separados ou campo único.

![image](https://user-images.githubusercontent.com/52920939/111483311-73b06300-8713-11eb-80ca-d699bf89cdd6.png)

**Comment by silviana-faria** [comment]
Conforme informado pelo analista Luiz (Prodemge) os campos são extraídos separadamente (descrição e código). Para representar a informação no Portal ele concatena as informações.

**Comment by kesiabomfa** [comment]
Ok, vou acrescentar essa informação na consulta de Diárias.

**Comment by kesiabomfa** [comment]
Informação confirmada com o Luís
